### ISSUE TITLE
有更详细的教程吗

### ISSUE THREAD

**Issue by lcm1475** [Can-Chen/wrap-midjourney#1]
go的这部分怎么使用有点懵 看文档也没看懂

**Comment by Can-Chen** [comment]
把你的疑问详细描述一下，我尽量全部解答

**Comment by lcm1475** [comment]
生成的时候自己请求api吗还是也用这个go的程序请求？
有其他联系方式吗 不太懂go

**Comment by Can-Chen** [comment]
这个程序只做一个中转 你就当一个黑盒用 
1. 配置好回调 这个请求会把对应的数据发送给这个回调post请求
2. 需要什么样的指令 发送对应的参数即可 同样也是post请求
type RequestTrigger struct {
	Type         string `json:"type"`
	DiscordMsgId string `json:"discordMsgId,omitempty"`
	MsgHash      string `json:"msgHash,omitempty"`
	Prompt       string `json:"prompt,omitempty"`
	Index        int64  `json:"index,omitempty"`
}
type代表你要触发什么指令
DiscordMsgId和MsgHash都在生图的时候传输给你了 主要是进行升级操作的时候需要
prompt就是你生图的提示词
index就是你进行升级操作的的时候选择的第几张图


我这没考虑到不熟悉go语言的作者 如何利用我这个项目去触发discord中的midjourney生图的详细操作 后续我会更新在文档中https://www.yuque.com/zsf9e3/amhz8b/mn5zkk7txztzeb0b#Io4OS

预计周五之前完成更新，请关注

**Comment by lcm1475** [comment]
好的 感谢解答 我希望的文档步骤是：
1.项目部署条件
2.key和回调URL的配置
3.如何发送prompt生成图
4.如何放大或重新生成图片
5.回调到url的参数示例
不知道我描述的是否清楚

**Comment by lcm1475** [comment]
好的 感谢解答 我希望的文档步骤是：
1.项目部署条件
2.key和回调URL的配置
3.如何发送prompt生成图
4.如何放大或重新生成图片
5.回调到url的参数示例
不知道我描述的是否清楚

**Comment by Can-Chen** [comment]
好的

**Comment by Get-wy** [comment]
你好，我想问一下 为什么我监听不到 content 内容？
<img width="220" alt="image" src="https://user-images.githubusercontent.com/36063518/231980647-97d9c47e-74a4-44c1-b8b5-ca46a0ab9bed.png">

**Comment by Get-wy** [comment]
> 好的

hi 你好，请问我问什么监听不到  content 内容？

**Comment by GuiJiDuoDuanZero** [comment]
> > 好的
> 
> hi 你好，请问我问什么监听不到 content 内容？

https://github.com/Can-Chen/wrap-midjourney/blob/master/handlers/discord.go
打印一下DiscordMsgCreate函数的内容

**Comment by GuiJiDuoDuanZero** [comment]
https://www.yuque.com/zsf9e3/amhz8b/mn5zkk7txztzeb0b#Io4OS 文档已更新

**Comment by Get-wy** [comment]
> > > 好的
> > 
> > 
> > hi 你好，请问我问什么监听不到 content 内容？
> 
> https://github.com/Can-Chen/wrap-midjourney/blob/master/handlers/discord.go 打印一下DiscordMsgCreate函数的内容

好的 谢谢
