### ISSUE TITLE
在钉钉里想要选择其中一个图片放大，怎么关联是哪个4选1图片呢

### ISSUE THREAD

**Issue by pengfeiu** [Can-Chen/wrap-midjourney#10]
如果是右键回复的方式，钉钉的参数有些是加密，没找到官方文档如何解密的

**Comment by pengfeiu** [comment]
我可能生成了多个4选1图片，我回复选择某个图片的时候，如何关联是哪个4选1呢

**Comment by Can-Chen** [comment]
回调参数中 有个字段https://pkg.go.dev/github.com/bwmarrin/discordgo#MessageReference 这个字段是对上一条消息的引用
