### ISSUE TITLE
DiscordMsgCreate和DiscordMsgUpdate都没有执行

### ISSUE THREAD

**Issue by crsec** [Can-Chen/wrap-midjourney#12]
func DiscordMsgCreate(s *discord.Session, m *discord.MessageCreate) {
	fmt.Println("DiscordMsgCreate triggered")

这个函数没进来是什么问题

**Comment by Can-Chen** [comment]
稍等 明天给你看一下

**Comment by Can-Chen** [comment]
https://www.yuque.com/zsf9e3/amhz8b/mn5zkk7txztzeb0b#comment-25489535
排查一下
