### ISSUE TITLE
指令出发mj的社区规则

### ISSUE THREAD

**Issue by yoke1990** [Can-Chen/wrap-midjourney#18]
![1684277085672](https://github.com/Can-Chen/wrap-midjourney/assets/10011855/7589ee2d-ac53-48aa-b239-b8c31b8c36a3)

当指令出发社区规则，不让执行。怎么设置，机器人才能获取到这个错误信息呢。
返回没有 (Stopped) 这个内容

**Comment by Can-Chen** [comment]
因为这个错误属于是发给个人的信息 我暂时没有方式拿到这个信息 如果能够拿到我会同步github的
问题是<<<!189!>>> 这种方式造成的 你可以试试<!id:189>试试

**Comment by ha5ky** [comment]
> 因为这个错误属于是发给个人的信息 我暂时没有方式拿到这个信息 如果能够拿到我会同步github的 问题是<<<!189!>>> 这种方式造成的 你可以试试<!id:189>试试

还是会出现这个问题，加了id:也不行
