### ISSUE TITLE
能否接收Job action restricted类型的消息呢？

### ISSUE THREAD

**Issue by hisune** [Can-Chen/wrap-midjourney#19]
![image](https://github.com/Can-Chen/wrap-midjourney/assets/7941669/e14e6a25-33d0-4046-b9f3-90b78458aa02)

类似上图，这种消息无法接收，无法判断任务是否正常在执行

**Comment by Can-Chen** [comment]
暂时拿不到 这个属于给个人发送的消息 非持久的 能够拿到了 我这里会更新的
