### ISSUE TITLE
midjourney AI

### ISSUE THREAD

**Issue by Can-Chen** [Can-Chen/wrap-midjourney#2]

**Comment by Can-Chen** [comment]
midjourney AI机器人出了一个 图转提示词的功能 /describe 
目前有两个问题未解决
1. 把图上传到discord服务器上 给的是一个临时地址 不是discord cdn地址
`{
    "type": 2,
    "application_id": "936929561302675456",
    "guild_id": "xx",
    "channel_id": "xx",
    "session_id": "b60af517799ac333be9abb896a15f134",
    "data": {
        "version": "1092492867185950853",
        "id": "1092492867185950852",
        "name": "describe",
        "type": 1,
        "options": [
            {
                "type": 11,
                "name": "image",
                "value": 0
            }
        ],
        "application_command": {
            "id": "1092492867185950852",
            "application_id": "936929561302675456",
            "version": "1092492867185950853",
            "default_member_permissions": null,
            "type": 1,
            "nsfw": false,
            "name": "describe",
            "description": "Writes a prompt based on your image.",
            "dm_permission": true,
            "options": [
                {
                    "type": 11,
                    "name": "image",
                    "description": "The image to describe",
                    "required": true
                }
            ]
        },
        "attachments": [
            {
                "id": "0",
                "filename": "test.png",
                "uploaded_filename": "5f587d99-1adb-4a57-81c7-7037b3464d5c/9b8e453bab5435a4.png"
            }
        ]
    }
}`
2. midjourney AI机器人回复的内容 不属于discord message 收不到推送
解决了的作者可以pr一下

**Comment by EchoAGI** [comment]
已解决. 留下您的vx

**Comment by EchoAGI** [comment]
1. 上传 attachments
2. 通过 interactions 端点 调用 /describe, /blend 也是一样
3. 监听 describe, blend message. 得到结果返回

**Comment by Can-Chen** [comment]
> 1. 上传 attachments
> 2. 通过 interactions 端点 调用 /describe, /blend 也是一样
> 3. 监听 describe, blend message. 得到结果返回

你上传是怎么解决的 attachments 配合 google storage

**Comment by Can-Chen** [comment]
/describe和/blend解决了

TODO：
/info

**Comment by zhangsong9008** [comment]
请问下，我的需求是上传一张图片，再给一个提示词，然后拿到mj的返回图片。也就是 `/imagine   图片地址   提示词` 这个功能，但是上传图片后不知道怎么拿到图片的url。请问这个要怎么解决？ @Can-Chen

**Comment by zhangsong9008** [comment]
我想上传一张图片，再给一个提示词，然后拿到mj的返回图片。也就是 `/imagine   图片地址   提示词` 这个功能，但是上传图片后不知道怎么拿到图片的url，楼主大神给下解决方法，谢谢！

**Comment by taigulilijie** [comment]
怎么联系到您 vx

**Comment by xhzth70911** [comment]
> /describe和/blend解决了
> 
> TODO： /信息

/info怎么解决,我直接改一个info的json,直接就报错:
response:  {"code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATION_COMMAND_INVALID", "message": "Invalid interaction application command"}]}}, "message": "Invalid Form B
ody"} <nil> 400 Bad Request

![(FPG 0HP)QZ5FF0`R}~K _X](https://github.com/Can-Chen/wrap-midjourney/assets/24982706/da86d17a-42ad-4d8e-9913-063f88edfadb)
