### ISSUE TITLE
一些神奇promt触发神奇BUG。

### ISSUE THREAD

**Issue by yoke1990** [Can-Chen/wrap-midjourney#21]
generate时候，个别提示词，例如：
Beside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. The water in the pool is clear and crystal clear, with sparkling waves. The figure of the beautiful woman is reflected in the water, forming a beautiful scene. The surrounding scenery is also very pleasant, with green trees shaded and the fragrance of flowers overflowing, making people feel relaxed and happy. The entire scene is full of summer atmosphere, It reminds people of those beautiful memories ,Eye Level Shot,Front view --ar 3:2

wrap-mid接收
可以收到：
	FirstTrigger Scene = "FirstTrigger"
也可以收到：
	DiscordMsgUpdate函数也能搜到updata

但是收不到：
	GenerateEnd
打印所有消息，err，确认没有
------------------
打印出来内容如下：
[GIN-debug] POST   /v1/trigger/midjourney-bot --> wrap-midjourney/handlers.MidjourneyBot (3 handlers)
[GIN-debug] POST   /v1/trigger/upload        --> wrap-midjourney/handlers.UploadFile (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :16007
response:   <nil> 204 No Content
[GIN] 2023/05/18 - 10:05:47 | 200 |  233.708892ms |    47.93.185.87 | POST     "/v1/trigger/midjourney-bot"
discord message:  {"id":"1108757335263952958","channel_id":"1106523777896030250","guild_id":"1106523777191395390","content":"**\u003c\u003c\u003c!514!\u003e\u003e\u003eBeside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. ,Eye Level Shot,Front view** - \u003c@369874892918620162\u003e (Waiting to start)","timestamp":"2023-05-18T14:05:48.442Z","edited_timestamp":null,"mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[],"embeds":[],"mentions":[{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":20,"webhook_id":"936929561302675456","member":{"guild_id":"","joined_at":"2023-05-12T10:19:24.415472Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1106526032393150546"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":{"id":"1108757332416004107","type":2,"name":"imagine","user":{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0},"member":{"guild_id":"","joined_at":"2023-05-12T10:10:26.72Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":[],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null}},"flags":0,"sticker_items":null}

discord message update:  {"id":"1108757335263952958","channel_id":"1106523777896030250","guild_id":"1106523777191395390","content":"**\u003c\u003c\u003c!514!\u003e\u003e\u003eBeside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. ,Eye Level Shot,Front view** - \u003c@369874892918620162\u003e (0%) (fast)","timestamp":"2023-05-18T14:05:48.442Z","edited_timestamp":"2023-05-18T14:06:03.808359Z","mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[{"id":"1108757399818489856","url":"https://cdn.discordapp.com/attachments/1106523777896030250/1108757399818489856/grid_0.webp","proxy_url":"https://media.discordapp.net/attachments/1106523777896030250/1108757399818489856/grid_0.webp","filename":"grid_0.webp","content_type":"image/webp","width":512,"height":512,"size":22986,"ephemeral":false}],"embeds":[],"mentions":[{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":20,"webhook_id":"936929561302675456","member":{"guild_id":"","joined_at":"2023-05-12T10:19:24.415472Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1106526032393150546"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":{"id":"1108757332416004107","type":2,"name":"imagine","user":{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0},"member":{"guild_id":"","joined_at":"2023-05-12T10:10:26.72Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":[],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null}},"flags":0,"sticker_items":null}

discord message update:  {"id":"1108757335263952958","channel_id":"1106523777896030250","guild_id":"1106523777191395390","content":"**\u003c\u003c\u003c!514!\u003e\u003e\u003eBeside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. ,Eye Level Shot,Front view** - \u003c@369874892918620162\u003e (15%) (fast)","timestamp":"2023-05-18T14:05:48.442Z","edited_timestamp":"2023-05-18T14:06:09.993061Z","mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[{"id":"1108757425986732073","url":"https://cdn.discordapp.com/attachments/1106523777896030250/1108757425986732073/grid_0.webp","proxy_url":"https://media.discordapp.net/attachments/1106523777896030250/1108757425986732073/grid_0.webp","filename":"grid_0.webp","content_type":"image/webp","width":512,"height":512,"size":32018,"ephemeral":false}],"embeds":[],"mentions":[{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":20,"webhook_id":"936929561302675456","member":{"guild_id":"","joined_at":"2023-05-12T10:19:24.415472Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1106526032393150546"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":{"id":"1108757332416004107","type":2,"name":"imagine","user":{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0},"member":{"guild_id":"","joined_at":"2023-05-12T10:10:26.72Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":[],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null}},"flags":0,"sticker_items":null}

discord message update:  {"id":"1108757335263952958","channel_id":"1106523777896030250","guild_id":"1106523777191395390","content":"**\u003c\u003c\u003c!514!\u003e\u003e\u003eBeside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. ,Eye Level Shot,Front view** - \u003c@369874892918620162\u003e (31%) (fast)","timestamp":"2023-05-18T14:05:48.442Z","edited_timestamp":"2023-05-18T14:06:12.906203Z","mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[{"id":"1108757438146019420","url":"https://cdn.discordapp.com/attachments/1106523777896030250/1108757438146019420/grid_0.webp","proxy_url":"https://media.discordapp.net/attachments/1106523777896030250/1108757438146019420/grid_0.webp","filename":"grid_0.webp","content_type":"image/webp","width":512,"height":512,"size":41370,"ephemeral":false}],"embeds":[],"mentions":[{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":20,"webhook_id":"936929561302675456","member":{"guild_id":"","joined_at":"2023-05-12T10:19:24.415472Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1106526032393150546"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":{"id":"1108757332416004107","type":2,"name":"imagine","user":{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0},"member":{"guild_id":"","joined_at":"2023-05-12T10:10:26.72Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":[],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null}},"flags":0,"sticker_items":null}

discord message update:  {"id":"1108757335263952958","channel_id":"1106523777896030250","guild_id":"1106523777191395390","content":"**\u003c\u003c\u003c!514!\u003e\u003e\u003eBeside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. ,Eye Level Shot,Front view** - \u003c@369874892918620162\u003e (46%) (fast)","timestamp":"2023-05-18T14:05:48.442Z","edited_timestamp":"2023-05-18T14:06:16.269031Z","mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[{"id":"1108757452155011082","url":"https://cdn.discordapp.com/attachments/1106523777896030250/1108757452155011082/grid_0.webp","proxy_url":"https://media.discordapp.net/attachments/1106523777896030250/1108757452155011082/grid_0.webp","filename":"grid_0.webp","content_type":"image/webp","width":512,"height":512,"size":50432,"ephemeral":false}],"embeds":[],"mentions":[{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":20,"webhook_id":"936929561302675456","member":{"guild_id":"","joined_at":"2023-05-12T10:19:24.415472Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1106526032393150546"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":{"id":"1108757332416004107","type":2,"name":"imagine","user":{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0},"member":{"guild_id":"","joined_at":"2023-05-12T10:10:26.72Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":[],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null}},"flags":0,"sticker_items":null}

discord message update:  {"id":"1108757335263952958","channel_id":"1106523777896030250","guild_id":"1106523777191395390","content":"**\u003c\u003c\u003c!514!\u003e\u003e\u003eBeside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. ,Eye Level Shot,Front view** - \u003c@369874892918620162\u003e (62%) (fast)","timestamp":"2023-05-18T14:05:48.442Z","edited_timestamp":"2023-05-18T14:06:19.711283Z","mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[{"id":"1108757466549858314","url":"https://cdn.discordapp.com/attachments/1106523777896030250/1108757466549858314/grid_0.webp","proxy_url":"https://media.discordapp.net/attachments/1106523777896030250/1108757466549858314/grid_0.webp","filename":"grid_0.webp","content_type":"image/webp","width":512,"height":512,"size":58996,"ephemeral":false}],"embeds":[],"mentions":[{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":20,"webhook_id":"936929561302675456","member":{"guild_id":"","joined_at":"2023-05-12T10:19:24.415472Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1106526032393150546"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":{"id":"1108757332416004107","type":2,"name":"imagine","user":{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0},"member":{"guild_id":"","joined_at":"2023-05-12T10:10:26.72Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":[],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null}},"flags":0,"sticker_items":null}

discord message update:  {"id":"1108757335263952958","channel_id":"1106523777896030250","guild_id":"1106523777191395390","content":"**\u003c\u003c\u003c!514!\u003e\u003e\u003eBeside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. ,Eye Level Shot,Front view** - \u003c@369874892918620162\u003e (78%) (fast)","timestamp":"2023-05-18T14:05:48.442Z","edited_timestamp":"2023-05-18T14:06:22.756541Z","mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[{"id":"1108757479610908752","url":"https://cdn.discordapp.com/attachments/1106523777896030250/1108757479610908752/grid_0.webp","proxy_url":"https://media.discordapp.net/attachments/1106523777896030250/1108757479610908752/grid_0.webp","filename":"grid_0.webp","content_type":"image/webp","width":512,"height":512,"size":67690,"ephemeral":false}],"embeds":[],"mentions":[{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":20,"webhook_id":"936929561302675456","member":{"guild_id":"","joined_at":"2023-05-12T10:19:24.415472Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1106526032393150546"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":{"id":"1108757332416004107","type":2,"name":"imagine","user":{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0},"member":{"guild_id":"","joined_at":"2023-05-12T10:10:26.72Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":[],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null}},"flags":0,"sticker_items":null}

discord message update:  {"id":"1108757335263952958","channel_id":"1106523777896030250","guild_id":"1106523777191395390","content":"**\u003c\u003c\u003c!514!\u003e\u003e\u003eBeside a spacious swimming pool, there is a beautiful woman wearing a bikini. She stands at the edge of the pool, holding onto the railing and slightly looking up, as if enjoying the warmth of the sun. ,Eye Level Shot,Front view** - \u003c@369874892918620162\u003e (93%) (fast)","timestamp":"2023-05-18T14:05:48.442Z","edited_timestamp":"2023-05-18T14:06:26.118748Z","mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[{"id":"1108757493485678743","url":"https://cdn.discordapp.com/attachments/1106523777896030250/1108757493485678743/grid_0.webp","proxy_url":"https://media.discordapp.net/attachments/1106523777896030250/1108757493485678743/grid_0.webp","filename":"grid_0.webp","content_type":"image/webp","width":512,"height":512,"size":87270,"ephemeral":false}],"embeds":[],"mentions":[{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":20,"webhook_id":"936929561302675456","member":{"guild_id":"","joined_at":"2023-05-12T10:19:24.415472Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1106526032393150546"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":{"id":"1108757332416004107","type":2,"name":"imagine","user":{"id":"369874892918620162","email":"","username":"alikuku","avatar":"","locale":"","discriminator":"9833","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0},"member":{"guild_id":"","joined_at":"2023-05-12T10:10:26.72Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":[],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null}},"flags":0,"sticker_items":null}

**Comment by yoke1990** [comment]
我测试很久
删掉 bikini 这个提示词。就是比基尼。就正常了

**Comment by Can-Chen** [comment]
看你的日志好像没有完成状态呀，你粘贴完整了吗？或者看一下你的discord客户端里面图片是否正常生成了

**Comment by yoke1990** [comment]
贴完整了，反复测试很多次，最后完成那个bot接不到。
研究半天，确认一些词命中规则。
mj觉得这个图可能带颜色或者暴力。只会给你个人看（only you can see，底部会有一小行字）。bot接收不到卡在最后93%
确认了
