### ISSUE TITLE
获取到discord中的图片资源传输给你的业务接口是啥，能做个说明吗？

### ISSUE THREAD

**Issue by BojianZhang** [Can-Chen/wrap-midjourney#22]
获取到discord中的图片资源传输给你的业务接口是啥，能做个说明吗？
![1684470719657](https://github.com/Can-Chen/wrap-midjourney/assets/81281872/10da23fc-336c-48af-8336-b29df6e144fa)

**Comment by hisune** [comment]
就是你自己的业务api，discord处理完图片后会把处理结果回调到你配置的这个url上

**Comment by Can-Chen** [comment]
https://github.com/ConnectAI-E/Feishu-Midjourney/blob/main/lark/handlers/personal.go#L209

**Comment by BojianZhang** [comment]
> 

还是不明白
