### ISSUE TITLE
/info 和敏感词多久能支持

### ISSUE THREAD

**Issue by xhzth70911** [Can-Chen/wrap-midjourney#28]
敏感词如果失败，代码里是不能收到返回消息的
![image](https://github.com/Can-Chen/wrap-midjourney/assets/24982706/36af64c7-5141-466a-aacd-c081d0df2f02)

/info怎么解决,我直接改一个info的json,直接就报错:
response: {"code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATION_COMMAND_INVALID", "message": "Invalid interaction application command"}]}}, "message": "Invalid Form B
ody"} 400 Bad Request
![1686104421328](https://github.com/Can-Chen/wrap-midjourney/assets/24982706/bfd3fce0-5708-47f8-835b-23f08e509d2e)

**Comment by Can-Chen** [comment]
最近比较忙 暂时没时间支持
