### ISSUE TITLE
session_id 从哪里获取呢

### ISSUE THREAD

**Issue by xwy007** [Can-Chen/wrap-midjourney#29]
session_id 从哪里获取呢，辛苦说下，双膝下跪求，谢谢

**Comment by Can-Chen** [comment]
什么session_id?

**Comment by xwy007** [comment]
> 什么是session_id？

![1686327233259](https://github.com/Can-Chen/wrap-midjourney/assets/31365171/79b852e6-b802-4e7d-bffc-570242ea4edf)
这里的这个参数怎么获取呢

**Comment by Can-Chen** [comment]
随便搞个就可以了 影响不大
