### ISSUE TITLE
请问配置好后启动程序后该如何使用呢，能写一个示例吗

### ISSUE THREAD

**Issue by stakeswky** [Can-Chen/wrap-midjourney#3]
rt

**Comment by GuiJiDuoDuanZero** [comment]
程序启动就好了 详细使用方式 我会出一个文档 关注readme地址

**Comment by GuiJiDuoDuanZero** [comment]
文档已更新https://www.yuque.com/zsf9e3/amhz8b/mn5zkk7txztzeb0b#Io4OS

**Comment by stakeswky** [comment]
请问yaml里的CB_URL指的是我服务器的地址吗，起到的是什么作用呢

**Comment by GuiJiDuoDuanZero** [comment]
把当前midjourney bot发送的消息发送给你 有三种 详细看https://github.com/Can-Chen/wrap-midjourney/blob/master/handlers/discord.go 代码
