### ISSUE TITLE
关于生成图片回调

### ISSUE THREAD

**Issue by mofung1** [Can-Chen/wrap-midjourney#31]
大佬，我看main.go里会有个LoadDiscordClient加载两个处理去请求discord，这里没怎么看明白，我看回调接口也是从这块发起请求的。这里获取到discord图片的逻辑是怎么样的呢？LoadDiscordClient这块逻辑可以详细说说吗？没搞懂获取discord图片的原理

**Comment by Can-Chen** [comment]
没搞懂获取discord图片的原理：利用discordgo这个sdk提供的方法监听频道的消息创建和更新 详细看代码
