### ISSUE TITLE
discord报错：has connected to Discord more than 1000 times within a short time period. 

### ISSUE THREAD

**Issue by ipeaking** [Can-Chen/wrap-midjourney#37]
今天早上收到discord的报错如下：
It appears your bot, xxxx, has connected to Discord more than 1000 times within a short time period. Since this kind of behavior is usually a result of a bug we have gone ahead and reset your bot's token.

请问这个如何解决

**Comment by Can-Chen** [comment]
这不是告诉你了吗 刷新一下你的机器人 token 更新一下就好了
