### ISSUE TITLE
接收bot信息无法json

### ISSUE THREAD

**Issue by yoke1990** [Can-Chen/wrap-midjourney#4]
哥们，你好。我测试下遇到
1.接收机器人消息时候出bug。DiscordMsgCreate 和 DiscordMsgUpdate出错
2.发送生成图片接口正常。能正常生成图片

我看了下代码，报错发生在这里
if data, err := json.Marshal(m); err == nil {
fmt.Println("discord message: ", string(data))
}

也就是转成json出错了

go日记打印出来的
discord message: {"id":"1097721905731084368","channel_id":"1095276446274048042","guild_id":"1095276445128982551","content":"","timestamp":"2023-04-18T03:14:57.013Z","edited_timestamp":null,"mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[],"embeds":[],"mentions":[{"id":"1094268987803713596","email":"","username":"adrtav","avatar":"","locale":"","discriminator":"2635","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":0,"webhook_id":"","member":{"guild_id":"","joined_at":"2023-04-11T09:18:13.275133Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1095276610556547125"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":null,"flags":0,"sticker_items":null}

**Comment by yoke1990** [comment]
当然也可能说，有效的返回消息没报错。

但是接收接口CB_URL，没有任何发送过来的内容

![image](https://user-images.githubusercontent.com/10011855/232664248-075529f9-4da9-41e5-87a1-1f1e1b5798ce.png)

**Comment by Can-Chen** [comment]
出现什么错误了

**Comment by Can-Chen** [comment]
是这样的 你这个discord的消息内容不是需要处理的类型

**Comment by Can-Chen** [comment]
https://github.com/Can-Chen/wrap-midjourney/blob/master/handlers/discord.go 你可以详细看一下这里面的代码。什么情况下会触发你的callback url

**Comment by yoke1990** [comment]
简单说，就是能发送指令生成图片，更新图片。
但是接收bot消息，出问题了。
CB_URL，我架设接口，没收到任何记录。

**Comment by Can-Chen** [comment]
拿到你的discord json不是一个需要处理的格式 具体的你看一下上面的我给的链接

**Comment by yoke1990** [comment]
代码我看了。
我向wrap-midjourney发送生成命令。也确实生成图片。这个应该触发callback。但是没触发就这个很奇怪。我再检查下把
