### ISSUE TITLE
机器人返回消息问题

### ISSUE THREAD

**Issue by sanguinedab** [Can-Chen/wrap-midjourney#5]
为什么bot返回的msg中content和attachments字段一直都是空的，但是discord中已经成功生成了

**Comment by Can-Chen** [comment]
提供一下discord message日志的内容 https://github.com/Can-Chen/wrap-midjourney/blob/master/handlers/discord.go 在这里打印的

**Comment by yoke1990** [comment]
哥们，我这里插一脚吧。白天随便跑下，今晚有空我把代码跟踪了一遍，也打印出来。
确实 content和attachments是空的。不知BOT设置问题。msg打印出来如下


{"id":"1097721905731084368","channel_id":"1095276446274048042","guild_id":"1095276445128982551","content":"","timestamp":"2023-04-18T03:14:57.013Z","edited_timestamp":null,"mention_roles":[],"tts":false,"mention_everyone":false,"author":{"id":"936929561302675456","email":"","username":"Midjourney Bot","avatar":"4a79ea7cd151474ff9f6e08339d69380","locale":"","discriminator":"9282","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":true,"public_flags":589824,"premium_type":0,"system":false,"flags":0},"attachments":[],"embeds":[],"mentions":[{"id":"1094268987803713596","email":"","username":"adrtav","avatar":"","locale":"","discriminator":"2635","token":"","verified":false,"mfa_enabled":false,"banner":"","accent_color":0,"bot":false,"public_flags":0,"premium_type":0,"system":false,"flags":0}],"reactions":null,"pinned":false,"type":0,"webhook_id":"","member":{"guild_id":"","joined_at":"2023-04-11T09:18:13.275133Z","nick":"","deaf":false,"mute":false,"avatar":"","user":null,"roles":["1095276610556547125"],"premium_since":null,"pending":false,"permissions":"0","communication_disabled_until":null},"mention_channels":null,"activity":null,"application":null,"message_reference":null,"referenced_message":null,"interaction":null,"flags":0,"sticker_items":null}

**Comment by Can-Chen** [comment]
方便我远程操作一下吗

**Comment by yoke1990** [comment]
可以，方便加个微信。我发向日葵
vx：yoke1990

**Comment by Can-Chen** [comment]
> 为什么bot返回的msg中content和attachments字段一直都是空的，但是discord中已经成功生成了

https://www.yuque.com/zsf9e3/amhz8b/mn5zkk7txztzeb0b#uHl0x 补了一下教程

**Comment by sanguinedab** [comment]
> > 为什么bot返回的msg中content和attachments字段一直都是空的，但是discord中已经成功生成了
> 
> https://www.yuque.com/zsf9e3/amhz8b/mn5zkk7txztzeb0b#uHl0x 补了一下教程

开启那个配置就好了是吗

**Comment by salyfine** [comment]
你好 是否可以加个微信 请教一下 jnfanye
