### ISSUE TITLE
本地运行discordClient.Open()报错

### ISSUE THREAD

**Issue by pengfeiu** [Can-Chen/wrap-midjourney#7]
本地运行discordClient.Open()报错
应该不是机器人token没写对
可能是代理问题，我尝试开启全局代理
// 设置全局代理
    proxyURL, _ := url.Parse("http://127.0.0.1:1080")
    http.DefaultTransport = &http.Transport{Proxy: http.ProxyURL(proxyURL)}
还是报错，但是mj的接口可以调通，生成了图片，请问怎么设置discordClient的代理

**Comment by pengfeiu** [comment]
golang.org/x/sys/windows.WSAETIMEDOUT (10060)

**Comment by pengfeiu** [comment]
不设置代理是这个报错：context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by pengfeiu** [comment]
设置代理是这个报错：golang.org/x/sys/windows.WSAETIMEDOUT (10060)

**Comment by Can-Chen** [comment]
https://www.yuque.com/zsf9e3/amhz8b/mn5zkk7txztzeb0b#comment-25489829

**Comment by pengfeiu** [comment]
> https://www.yuque.com/zsf9e3/amhz8b/mn5zkk7txztzeb0b#comment-25489829
这个试了，只能调通GenerateImage方法，discord是能生成图片，但是discord机器人连接不上，生成出来的图片，无法回调接口
err = discordClient.Open()
	if err != nil {
		fmt.Println("error opening connection,", err)  // err报错
		return
	}

**Comment by Can-Chen** [comment]
sorry 完整的看了一下你的问题 应该就是网络的问题 你可以在文档下方找那个已经解决问题的用户 他的代理是如何设置的

**Comment by Can-Chen** [comment]
sorry 完整的看了一下你的问题 应该就是网络的问题 你可以在文档下方找那个已经解决问题的用户沟通一下他的代理是如何设置的

**Comment by pengfeiu** [comment]
好的，我看看，我刚才又检查了下bot的设置，发现MESSAGE CONTENT INTENT没有打开，保存，我改了一下，不过还是不行。

**Comment by l269438** [comment]
请问这个问题解决了吗，我这里也出现了。有解决方法吗

**Comment by Can-Chen** [comment]
网络的问题 你部署海外的服务器就好了

**Comment by l269438** [comment]
> 网络的问题 你部署海外的服务器就好了

已解决谢谢作者
