### ISSUE TITLE
能不能实现提交时加一个参数，在回调时将该参数合并发回去。

### ISSUE THREAD

**Issue by brianiser** [Can-Chen/wrap-midjourney#8]
不懂go语言，只能大概看懂一些，不知道该怎么改可以实现，请作者指导一下

**Comment by binglww** [comment]
有同样的需求，但是 https://discord.com/api/v9/interactions 接口不会返回任何数据，这样就没办法做关联，不知道作者有没有更好的方法

**Comment by Can-Chen** [comment]
我这里是在传入prompt的时候 加了前缀 然后回调的时候discord message content字段中会回传你的prompt 解析一下就可以了

**Comment by brianiser** [comment]
> 我这里是在传入prompt的时候 加了前缀 然后回调的时候discord message content字段中会回传你的prompt 解析一下就可以了

非常感谢作者，瞬间发现新大陆了

**Comment by lcm1475** [comment]
传入prompt的时候 加了前缀 不会影响生成的图片吗？ 类似于
原：prompt=》’a cute cat‘
现：prompt=》’[id:8888]a cute cat‘

**Comment by Can-Chen** [comment]
测试过 暂时没有太大的影响 [id: xxxx] url... prompt... param...

**Comment by lcm1475** [comment]
okok 非常感谢 我理解的没错吧
